### ISSUE TITLE
Questions about Trajectory Predictior (Physical Trajectory Predictor for Commands (PTPC)) module

### ISSUE THREAD

**Issue by Petrichor625** [ThierryDeruyttere/Talk2Car-Trajectory#1]
Thank you for your wonderful work!
We are so inspired by your work!
I would like to ask if it is possible to open source the code of the trajectory prediction module (Physical Trajectory Predictor for Commands **(PTPC)**), it would help us a lot, thanks for your answer!

**Comment by ThierryDeruyttere** [comment]
Hi!

Thanks for the interest in our work!
I'll have a look at this next week! Do remind me if I don't say anything next week!

**Comment by Petrichor625** [comment]
@ThierryDeruyttere, OK! Thanks for your help, I am looking forward to your further reply next week!

**Comment by Petrichor625** [comment]
@ThierryDeruyttere, OK! Thanks for your help, I am looking forward to your further reply next week!

**Comment by ThierryDeruyttere** [comment]
@Petrichor625 Hi, I uploaded the ptpc code currently as-is. You can find it here https://github.com/ThierryDeruyttere/Talk2Car-Trajectory/tree/master/ptpc
I also included a link to the checkpoint of the best-performing model

**Comment by Petrichor625** [comment]
@ThierryDeruyttere Sincerely thank you for your help! It really helped us a lot. Good luck with your graduation!
