### ISSUE TITLE
About the Test Set

### ISSUE THREAD

**Issue by Petrichor625** [ThierryDeruyttere/Talk2Car-Trajectory#2]
This is a pretty awesome work!
We found that in the test set, there is no ground truth data provided about the predicted trajectories and the corresponding ground truth referred object in the frontal image, however, there is no official website where we can submit our test results to evaluate the performance of our model.
Could you please tell me if have any ground truth of the test set or related website to submit the prediction results so that we can test the performance of the model?
Thank you for your answer, it will help us a lot to follow this work!

**Comment by ThierryDeruyttere** [comment]
Hi there!

Yes, we didn't upload it back then because we were unsure what we were going to do i.e., do we want to hold a challenge or something.
I'll upload the test data next week (but here too, send me a message if you do not hear back from me by end of next week. I'm not with the university anymore as I graduated from my PhD so I have other things that can come in between).

**Comment by ThierryDeruyttere** [comment]
Actually found time to do it right now.
Here are the files: https://drive.google.com/file/d/1XMu3z8ywGjOWlcONnzCmqtsL6vALuuLk/view?usp=sharing

Also updated the readme.

**Comment by Petrichor625** [comment]
@ThierryDeruyttere  Congratulations on your upcoming graduation and thank you for all your help. I have found that I need further verification after clicking on this Google link, I have submitted a request and would also like to ask you to authorize my account if possible, thank you very much!

**Comment by ThierryDeruyttere** [comment]
Sorry about that. You should have access now and I updated the link in the readme. 
Here it is also for your convenience: https://drive.google.com/file/d/1XMu3z8ywGjOWlcONnzCmqtsL6vALuuLk/view?usp=sharing
