### ISSUE TITLE
Issues about the dataset of PTPC 

### ISSUE THREAD

**Issue by Hearum** [ThierryDeruyttere/Talk2Car-Trajectory#3]
Thank you for your outstanding work!

While running the PTPC code, I encountered an issue regarding a missing file named 'val_spline_path_400cm.json'. Others like "fcos3d_t2c_boxes.json". We donot konw whether these files are necessary for the project. Could you kindly guide me on where I might obtain this dataset file ?
Specifically, at line 117 in the file ./Talk2Car-Trajectory/ptpc/talk2car.py, the code appears as follows:

`self.data = list(json.load(open(os.path.join(dataset_root, f"{split}_spline_path_400cm.json"), "r")).values())`

I appreciate your assistance in this matter. Thank you!

**Comment by ThierryDeruyttere** [comment]
Hi Haerum,

Yes the code was provided as-is because of lack of time.
I'll try to work on this next week to make it fully work out of the box.
Ping me on next Friday if I haven't posted anything.

**Comment by ThierryDeruyttere** [comment]
Hi @Hearum, please redownload all code and data. I've also added a requirements.txt file in the ptpc directory and updated the readme there too. Please have a look
