### ISSUE TITLE
Question about the json files in PTPC

### ISSUE THREAD

**Issue by Petrichor625** [ThierryDeruyttere/Talk2Car-Trajectory#4]
Thank you for your previous answers.
We found that many JSON source files are missing from talk2car.py in the PTPC code you provided. 
Could you please provide these files? Thank you very much!
![question](https://github.com/ThierryDeruyttere/Talk2Car-Trajectory/assets/120699340/57ae6777-7ab7-4a5b-8737-5542ab03947f)

**Comment by ThierryDeruyttere** [comment]
Hi @Petrichor625 I have updated the repository. Please re-download all files (dataset and code).

**Comment by Petrichor625** [comment]
Thank you very much for your help, sorry for the late reply!
